name: Build and Release on Push

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find JAR file (Linux)
        if: ${{ runner.os == 'Linux' }}
        id: find_jar_linux
        run: |
          JAR_FILE=$(find build/libs/ -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar")
          echo "JAR_FILE=$JAR_FILE" >> "$GITHUB_OUTPUT"

      - name: Find JAR file (Windows)
        if: ${{ runner.os == 'Windows' }}
        id: find_jar_windows
        run: |
          $jarFiles = Get-ChildItem -Path "build\libs\*.jar" -Exclude "*-sources.jar", "*-javadoc.jar"
          if ($jarFiles) {
            $latestJar = $jarFiles | Sort-Object LastWriteTime -Descending | Select-Object -First 1
            echo "JAR_FILE=$($latestJar.FullName)" | Out-File -Encoding UTF8 -Append -FilePath $env:GITHUB_OUTPUT
          } else {
            echo "JAR_FILE=" | Out-File -Encoding UTF8 -Append -FilePath $env:GITHUB_OUTPUT
          }

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-app
          path: ${{ steps.find_jar_linux.outputs.JAR_FILE || steps.find_jar_windows.outputs.JAR_FILE }}
        if: ${{ steps.find_jar_linux.outputs.JAR_FILE != '' || steps.find_jar_windows.outputs.JAR_FILE != '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Linux JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest-app
          path: linux_jar

      - name: Download Windows JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-app
          path: windows_jar

      - name: Get Linux JAR filename
        id: linux_jar_info
        run: |
          LINUX_JAR=$(ls linux_jar/*.jar)
          echo "asset_name=$(basename "$LINUX_JAR")" >> "$GITHUB_OUTPUT"

      - name: Get Windows JAR filename
        id: windows_jar_info
        run: |
          WINDOWS_JAR=$(ls windows_jar/*.jar)
          echo "asset_name=$(basename "$WINDOWS_JAR")" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }} # Use the commit SHA as the tag
          release_name: Bomberman-${{ github.run_number }}
          body: |
            JAR files built from commit ${{ github.sha }}.
            - Linux: ${{ steps.linux_jar_info.outputs.asset_name }}
            - Windows: ${{ steps.windows_jar_info.outputs.asset_name }}
          draft: false
          prerelease: true # Mark as a pre-release since it's on every push
          files: |
            linux_jar/${{ steps.linux_jar_info.outputs.asset_name }}
            windows_jar/${{ steps.windows_jar_info.outputs.asset_name }}